- hosts: k8m1 
  become: yes
  gather_facts: false
  tasks:
    - name: install Pod network
      shell: kubectl --kubeconfig /home/ubuntu/.kube/config apply -f  flannel.yml | tee pod_network_setup.txt
      args:
        chdir: /home/ubuntu
        creates: pod_network_setup.txt

    - name: Get the join command for additional Control planes
      shell: echo $(kubeadm token create --print-join-command) --control-plane --certificate-key $(kubeadm init phase upload-certs --upload-certs | grep -vw -e certificate -e Namespace)| tee control-plane

    - name: Get join command for workers
      shell: kubeadm token create --print-join-command | tee workers

   #- name: set join command
   #   set_fact:
   #     join_command: "{{ join_command_raw.stdout_lines[0] }}"

        # - name: Copy join command to local file
        #become: yes
        #local_action: copy content="{{join_command.stdout_lines[0]}}" dest="ansible/local-join-command"
    - name: Fetch the control-plane token file to local host    
      fetch:
        src: "control-plane"
        dest: "control-plane"

    - name: Fetch the token file to local host    
      fetch:
        src: "workers"
        dest: "workers"

- hosts: k8m2,k8m3 
  become: yes
  tasks:
    - name: Copy the control-plane join command to server location
      copy: src=./control-plane/k8m1/control-plane dest=/tmp/control-plane.sh mode=0777

    - name: Join the control-plane nodes to cluster
      command: sh /tmp/control-plane.sh

    - name: create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        mode: 0755
        owner: ubuntu

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

- hosts: workers 
  become: yes
  tasks:
    #- name: join cluster
    #  shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
    #  args:
    #    chdir: $HOME
    #    creates: node_joined.txt

    - name: Copy the workers join command to server location
      copy: src=./workers/k8m1/workers dest=/tmp/workers.sh mode=0777

    - name: Join the worker nodes to cluster
      command: sh /tmp/workers.sh
